# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-25 12:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calcio_splash', '0003_goal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tuornament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('edition_year', models.IntegerField()),
                ('edition_name', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='next_match',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prev_match', to='calcio_splash.Match'),
        ),
    ]
