# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-25 12:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calcio_splash', '0004_auto_20170425_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='calcio_splash.Match'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='calcio_splash.Player'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='calcio_splash.Team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='next_match',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prev_matches', to='calcio_splash.Match'),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_a', to='calcio_splash.Team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_b', to='calcio_splash.Team'),
        ),
    ]
