# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-20 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calcio_splash', '0008_team_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='start_secondo_tempo',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
