# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-20 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calcio_splash', '0009_auto_20170720_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='end_secondo_tempo',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
