# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-20 16:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calcio_splash', '0010_match_end_secondo_tempo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='end_secondo_tempo',
            new_name='end_primo_tempo',
        ),
    ]
