# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-21 18:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calcio_splash', '0011_auto_20170720_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='goalkeeper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goalkeeper', to='calcio_splash.Player'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='team_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rankings_1', to='calcio_splash.Team'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='team_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rankings_2', to='calcio_splash.Team'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='team_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rankings_3', to='calcio_splash.Team'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='top_scorer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='top_scorer', to='calcio_splash.Player'),
        ),
    ]
