# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-23 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calcio_splash', '0012_auto_20170721_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='is_final',
            field=models.BooleanField(default=False),
        ),
    ]
