# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-15 17:14
from __future__ import unicode_literals

from django.db import migrations, models


from django.db import migrations, models


def initialize_teams(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Player = apps.get_model('calcio_splash', 'Player')

    for player in Player.objects.all():
        player.teams = [player.team]
        player.save()


class Migration(migrations.Migration):
    dependencies = [
        ('calcio_splash', '0015_team_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='teams',
            field=models.ManyToManyField(related_name='players', to='calcio_splash.Team'),
        ),
        migrations.RunPython(initialize_teams),

    ]
