# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-16 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calcio_splash', '0017_delete_player_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='teams',
            field=models.ManyToManyField(blank=True, null=True, related_name='player', to='calcio_splash.Team'),
        ),
    ]
