# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-18 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calcio_splash', '0018_auto_20180616_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='gender',
            field=models.CharField(choices=[('M', 'Maschile'), ('F', 'Femminile'), ('B', 'Beach Volley')], default='M', max_length=2),
        ),
    ]
