# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-28 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calcio_splash', '0020_beachmatch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beachmatch',
            name='team_a_set_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='beachmatch',
            name='team_a_set_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='beachmatch',
            name='team_a_set_3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='beachmatch',
            name='team_b_set_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='beachmatch',
            name='team_b_set_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='beachmatch',
            name='team_b_set_3',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
