# Generated by Django 4.0 on 2022-05-20 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calcio_splash', '0021_auto_20190728_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='next_match',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prev_matches', to='calcio_splash.match'),
        ),
        migrations.AlterField(
            model_name='player',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='player', to='calcio_splash.Team'),
        ),
    ]
