# Generated by Django 4.0.4 on 2022-07-24 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calcio_splash', '0023_alter_beachmatch_options_alter_match_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='next_match',
        ),
    ]
