# Generated by Django 4.0.4 on 2022-07-24 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calcio_splash', '0025_alter_match_team_a_alter_match_team_b'),
    ]

    operations = [
        migrations.AddField(
            model_name='beachmatch',
            name='ended',
            field=models.BooleanField(default=False),
        ),
    ]
