# Generated by Django 4.0.6 on 2023-06-15 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calcio_splash', '0027_alter_beachmatch_team_a_alter_beachmatch_team_b'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ('ordering', 'pk')},
        ),
        migrations.AddField(
            model_name='group',
            name='ordering',
            field=models.IntegerField(default=0),
        ),
    ]
