# Generated by Django 4.2.14 on 2024-07-09 15:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('calcio_splash', '0028_alter_group_options_group_ordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='nickname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
