# Generated by Django 4.2.14 on 2024-08-04 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calcio_splash', '0030_match_brackets_offset'),
    ]

    operations = [
        migrations.AddField(
            model_name='beachmatch',
            name='brackets_offset',
            field=models.IntegerField(default=0),
        ),
    ]
