# Generated by Django 5.2.3 on 2026-07-30 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calcio_splash', '0031_beachmatch_brackets_offset'),
    ]

    operations = [
        migrations.AddField(
            model_name='beachmatch',
            name='team_a_notes',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='beachmatch',
            name='team_b_notes',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='match',
            name='team_a_notes',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='match',
            name='team_b_notes',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
